### ISSUE TITLE
No model named lib.nms

### ISSUE THREAD

**Issue by zhu2014yi** [pjl1995/CTracker#1]
Hi   ! 很棒的工作，但是我遇到了问题如下，可否解答一下
warnings.warn(msg, SourceChangeWarning)
CUDA available: True
Traceback (most recent call last):
  File "/home/xx/Code/CTracker/test.py", line 319, in <module>
    main()
  File "/home/xx/Code/CTracker/test.py", line 305, in main
    retinanet = torch.load(os.path.join(parser.model_dir, 'model_final.pt'))
  File "/home/xx/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/xx/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
  File "/home/xx/Code/CTracker/model.py", line 10, in <module>
    from lib.nms import cython_soft_nms_wrapper
ModuleNotFoundError: No module named 'lib.nms'

**Comment by Jubird915** [comment]
@pjl1995 run the command 
sh lib/build.sh
not work

@zhu2014yi 
could you share your solution how you copied the simpledet, I mean simpledet is a large project

**Comment by pjl1995** [comment]
What is the log output after you run the command sh lib/build.sh ?
@Jubird915

**Comment by pjl1995** [comment]
What is your pytorch version？
@Jubird915

**Comment by zhu2014yi** [comment]
> @pjl1995 run the command
> sh lib/build.sh
> not work
> 
> @zhu2014yi
> could you share your solution how you copied the simpledet, I mean simpledet is a large project
In simpledet/operator_py/cython

**Comment by pjl1995** [comment]
Hi all, I am so sorry that I forgot to add the nms.py in the lib folder. Now this bug is fixed and you can download the latest code.
